# Alacritty - TOML configuration file format.
#
# Alacritty's configuration file uses the TOML format.
# The format's specification can be found at https://toml.io/en/v1.0.0.
#
# See: man 5 alacritty or https://alacritty.org/config-alacritty.html
#
# by brainf+ck | Update: 2024/11/10

[env]
TERM = "alacritty"

[window]
#dimensions = { columns = 85, lines = 30 }
padding = { x = 1, y = 1 }

[scrolling]
history = 10000

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold italic" }
size = 9

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#535965"
blue = "#4fa6ed"
cyan = "#48b0bd"
green = "#8ebd6b"
magenta = "#bf68d9"
red = "#e55561"
white = "#b2bbcc"
yellow = "#e2b86b"

[colors.normal]
black = "#0e1013"
blue = "#4fa6ed"
cyan = "#48b0bd"
green = "#8ebd6b"
magenta = "#bf68d9"
red = "#e55561"
white = "#b2bbcc"
yellow = "#e2b86b"

[colors.primary]
background = "#1f2329"
foreground = "#b2bbcc"

[cursor]
style = { shape = "Block", blinking = "Off" }
